# Generated by Django 2.0.5 on 2018-05-26 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('rut', models.CharField(max_length=10)),
                ('nickname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nickname', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('rut', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('photo', models.ImageField(upload_to='photos')),
                ('game_position', models.CharField(choices=[('BASE', 'Base'), ('ESC', 'Escolta'), ('ALE', 'Alero'), ('ALP', 'Ala-pivot'), ('PIV', 'Pivot')], default='BASE', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('logo', models.ImageField(upload_to='img_logo')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='player',
            field=models.ManyToManyField(to='team.Player'),
        ),
        migrations.AddField(
            model_name='coach',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
        migrations.AddField(
            model_name='coach',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
