# Generated by Django 2.0.5 on 2018-05-26 02:53

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCoach',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='coach',
            name='user',
        ),
    ]
