# Generated by Django 2.0.4 on 2018-04-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(height_field=100, upload_to='static/media', width_field=100),
        ),
    ]
