# Generated by Django 2.0.4 on 2018-04-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20180420_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(upload_to='static/media'),
        ),
    ]
