# Generated by Django 2.0.5 on 2018-05-31 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20180531_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'permissions': (('edit_rost', 'Edit Rost'), ('add_rost', 'Add Rost'), ('delete_rost', 'Delete Rost'))},
        ),
        migrations.RemoveField(
            model_name='coach',
            name='perms',
        ),
    ]
