# Generated by Django 2.0.5 on 2018-05-31 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20180531_2336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={},
        ),
    ]
