# Generated by Django 2.0.4 on 2018-05-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20180516_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(upload_to='img_logo'),
        ),
    ]
