# Generated by Django 2.0.5 on 2018-05-31 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20180526_0323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Coach')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Game')),
                ('player', models.ManyToManyField(to='team.Player')),
            ],
        ),
    ]
