# Generated by Django 2.0.4 on 2018-05-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_auto_20180516_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(upload_to='media'),
        ),
    ]
