# Generated by Django 2.0.4 on 2018-05-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_auto_20180516_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
